export const stacks=[
    {
        id:1,
        img:"/stacks/html.svg"
    },
    {
        id:2,
        img:"/stacks/style.svg"
    },
    {
        id:3,
        img:"/stacks/js.svg"
    },
    {
        id:4,
        img:"/stacks/tailwindcss.svg"
    },
    {
        id:5,
        img:"/stacks/boot.svg"
    },
    {
        id:6,
        img:"/stacks/react.svg"
    },
    {
        id:7,
        img:"/stacks/sass.svg"
    },
    {
        id:8,
        img:"/stacks/py.svg"
    },
    {
        id:9,
        img:"/stacks/java.svg"
    },
    {
        id:10,
        img:"/stacks/node.svg"
    },
    {
        id:11,
        img:"/stacks/sql.svg"
    },
    {
        id:12,
        img:"/stacks/nextjs.svg"
    },
    {
        id:13,
        img:"/stacks/graphql.svg"
    },
    
]

export const tools=[
    {
        id:1,
        img:"/Tools/figma.svg"
    },
    {
        id:2,
        img:"/Tools/Github.svg"
    },
    {
        id:3,
        img:"/Tools/pycharm.svg"
    },
    {
        id:4,
        img:"/Tools/vscode.svg"
    },
    {
        id:5,
        img:"/Tools/window.svg"
    },
    {
        id:6,
        img:"/Tools/excel.svg"
    },
]